# Generated by Django 5.0 on 2023-12-14 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="complaint",
            name="customer",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="Complaint",
        ),
        migrations.DeleteModel(
            name="Customer",
        ),
    ]
